# Changes here will be overwritten by Copier
_commit: 37ad578
_src_path: https://github.com/python-project-templates/base.git
add_extension: python
email: 3105306+timkpaine@users.noreply.github.com
github: dau-dev
project_description: A package for packaging, organizing, and combining artifacts
project_name: artlink
python_version_primary: '3.11'
team: the artlink authors
