# Changes here will be overwritten by Copier
_commit: 973c39c
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: 3105306+timkpaine@users.noreply.github.com
github: dau-dev
project_description: A package for packaging, organizing, and combining artifacts
project_name: artlink
python_version_primary: '3.11'
team: the artlink authors
